### ISSUE TITLE
关于首页的文章简述问题

### ISSUE THREAD

**Issue by ghost** [link9596/jekyll-theme-Hydrogen#10]
又来打搅您了真的不好意思（是我基本功太菜了QwQ）
是这样的：我在博客上分别传了两篇文章，但是首页中文章简述完全不同。一篇就很简短，把`<blockquote>`输出就结束了，但是另一篇几乎把文章正文的所有东西都放上去了……这个应该在哪里修改啊，因为网上似乎只有一个人和我这个问题相似，而且目前好像还没解决……

**Comment by ghost** [comment]
查看源码中的情况就这样子：
![QQ截图20200718085930](https://user-images.githubusercontent.com/68377656/87841043-2efad080-c8d5-11ea-94d0-42ba75654d2d.png)
`span`标签明显位置不一样，但是应该怎么修改啊……

**Comment by link9596** [comment]
博客的摘要机制是取第一个空行前的文字，就是说第一次敲两下回车，回车前的就是摘要

**Comment by ghost** [comment]
emmmm并没有用，我无论是添加键盘上的回车还是用换行符好像都没用。我现在用的方法是直接添加post属性中的excerpt，但是和原来的效果不一样。

![QQ截图20200718113303](https://user-images.githubusercontent.com/68377656/87843887-95d6b480-c8ea-11ea-9be9-b060ed060828.png)
上面那个是加excerpt的，下面的是没加，但是不知道是怎么弄出来的……下面这个图是md的头
![QQ截图20200718113536](https://user-images.githubusercontent.com/68377656/87843933-e6e6a880-c8ea-11ea-9226-0d2d2096122a.png)

**Comment by link9596** [comment]
我将你的博客fork过来测试了一下，然后发现一个很神奇的问题，无论我怎么修改都会是这样，但是我将你的博文原文复制下来重新发布，就会恢复正常(问号脸)

**Comment by ghost** [comment]
我人傻了……那我删了重发布一次吧……

**Comment by link9596** [comment]
你看一下pull request，我给你发了一个。如果这篇文章还是不能正常显示请尝试同意请求。另外可以说一下你是用什么方式发布文章的呢🤔️网页or客户端？文章中的回车(换行符)有可能在发布文章时候被换掉了，导致github的markdown渲染器没有办法识别你的回车

**Comment by ghost** [comment]
我这边同意了，但是merge失败了？我正在查原因。
我用的网站发布的

**Comment by link9596** [comment]
因为我们两个的文章是一样的，您可以吧您那篇文章先删掉，然后就可以正常merge了~

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68377656/87847411-9bdc8d80-c90a-11ea-9ddf-5b7f6b40786a.png)
emmmmm

**Comment by ghost** [comment]
删了也merge不了 不删报冲突也解决不了……

**Comment by ghost** [comment]
迷迷糊糊的解决了，忽然就能merge了……
您费心了！万分感谢！
