### ISSUE TITLE
求问一下怎么用...

### ISSUE THREAD

**Issue by leledeyuan00** [link9596/jekyll-theme-Hydrogen#11]
我试着通过

`gem build Hy...gemspec`

和

`gem install ./Ma....`

然后

`jekyll serve`

但是出来的页面很奇怪，求指教....

![image](https://user-images.githubusercontent.com/26294903/160141346-72551870-451f-4613-89bf-859d3628d8da.png)

**Comment by link9596** [comment]
不知道你解决了没有，这个应该是css文件没有写好😂这个可以去根目录下的_config.yml里修改一下网站地址~

**Comment by link9596** [comment]
说错了，是css目录没有写好导致404了😂

**Comment by leledeyuan00** [comment]
嗯嗯！ 我改了改 config 和 default 里的，都删掉之后，就可以先在本地看到效果了！ 哈哈 非常非常感谢！
