### ISSUE TITLE
代码块的复制功能申请实装

### ISSUE THREAD

**Issue by LingASDJ** [link9596/jekyll-theme-Hydrogen#13]
你好，我正在使用你的博客引擎，她非常不错。但是在某些情况下，还是有一些问题。隶属于代码块的结构，目前仍然没有一键复制。希望你能在空暇时间看看实装方案。谢谢。

**Comment by link9596** [comment]
下个版本会考虑加入喔

**Comment by link9596** [comment]
已更新，可通过`/assets/js/core.js`的第二行修改匹配标签

**Comment by LingASDJ** [comment]
好的，谢谢作者大大。
