### ISSUE TITLE
好像有一些问题呢

### ISSUE THREAD

**Issue by Sunbertrs** [link9596/jekyll-theme-Hydrogen#2]
私はお試しください使用すHydrogenとして私のJekyllブログ、でもいまはこのように.....
解決方法は？私はこのテーマが本当に好きです。
![Screenshot_2019-09-13-20-59-50](https://user-images.githubusercontent.com/38691765/64864971-daf6de00-d66a-11e9-9d0b-6e0abc82a8fe.png)

**Comment by Sunbertrs** [comment]
再試行cloneの必要？

**Comment by Sunbertrs** [comment]
試行い後、はです...
![Screenshot_2019-09-13-21-23-16](https://user-images.githubusercontent.com/38691765/64865874-e814cc80-d66c-11e9-8f33-d09263fbedf0.png)

**Comment by link9596** [comment]
由于前段时间的忙碌和没有收到github的消息通知，深感抱歉我没有能及时回复您的消息！您的博客出现这种原因的可能是您没有在config.yml文件里正确配置您的域名和准确网址，导致css无法正常加载(404)谢谢您对hydrogen的热爱！(˶‾᷄ ⁻̫ ‾᷅˵)
