### ISSUE TITLE
Can't set a new favicon :(

### ISSUE THREAD

**Issue by ghost** [link9596/jekyll-theme-Hydrogen#3]
Hi!,  
I have a problem changing the "favicon", when I replaced the file with a new one, the "h2" icon still appeared. Already tried deleting the cache, and opening the page in another browser.
Ayuda! 

Thanks! :heart:

**Comment by Sunbertrs** [comment]
@kawaiiloser Hi! I am starting to use this Jekyll theme recently. And I am not edit the favicon yet. May I ask you, did you edit the favicon in the path ./avatar/ ?

**Comment by Sunbertrs** [comment]
BTW the favicon support the resolution like 32x32, 64x64, 128x128, 256x256 best.

**Comment by ghost** [comment]
> @kawaiiloser Hi! I am starting to use this Jekyll theme recently. And I am not edit the favicon yet. May I ask you, did you edit the favicon in the path ./avatar/ ?

Hi @SunbossRS, yes i upload a new favicon manually, but the resolutions is a little big, this is the png:
 https://github.com/kawaiiloser/kawaiiloser.github.io/blob/master/avatar/favicon.png

**Comment by ghost** [comment]
> BTW the favicon support the resolution like 32x32, 64x64, 128x128, 256x256 best.

So, i will try with any of this, i'll let you know if it works.

Ty!!

**Comment by ghost** [comment]
Fixed!!
In  /_layouts/default.html
then go to the line number 30, and replace the href link for your favicon link

**Comment by link9596** [comment]
I'm sorry that I didn't respond to your questions in time because GitHub didn't notify me of a new issue by email!
I'm glad that your problem has been solved. In the next version, I will add it to the configuration file to facilitate users!
Thank you for your enthusiasm for hydrogen❤️
