### ISSUE TITLE
请问如何移除“主题配置”和“Hydrogen”标签以及内容

### ISSUE THREAD

**Issue by Joe-Jack** [link9596/jekyll-theme-Hydrogen#8]
如题

**Comment by link9596** [comment]
主题配置文件在`/config/infor.html`里，hydrogen页面是根目录的`readme.md`，其他的页面在pages文件夹里，如果想删除直接删除以上对应的文件即可

**Comment by Joe-Jack** [comment]
谢谢大佬！顺便想问问你的留言板音乐播放器好像不能使用了，我点的时候没反应。如果我自己想添加音乐播放器，可否有相应的教程推荐呢？

**Comment by link9596** [comment]
留言板播放器是网易云的外链播放器，不知道为啥手机点击播放有bug233，如果你不想用网易云，我可以推荐你用[cplayer](https://cplayer.js.org/)，官网有很详细的教程，不过我也没具体研究怎么用过😂你可以看看

**Comment by Joe-Jack** [comment]
好的，谢谢！期待你后续的更新！

**Comment by link9596** [comment]
好滴，谢谢对主题的支持吖~

**Comment by Joe-Jack** [comment]
再次感谢，那么我将问题关闭了哦！
