### ISSUE TITLE
更改标签页的图标

### ISSUE THREAD

**Issue by ghost** [link9596/jekyll-theme-Hydrogen#9]
想问一下，标签页上的小水滴可以更改嘛？
![image](https://user-images.githubusercontent.com/68377656/87674868-302edf00-c7a9-11ea-9732-28863575d04a.png)

**Comment by link9596** [comment]
当然可以，文件是`/avatar/favicon.png`，把这个替换成你想要的图标就可以了✌

**Comment by ghost** [comment]
好的非常感谢！
